### ISSUE TITLE
problem during error treatment

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#121]
```python
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_spectrum_query.py", line 166, in build_list_from_ddosa_res
    np_spec = NumpyDataProduct.from_fits_file(spec_filename, meta_data=meta_data)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/oda_api/data_products.py", line 569, in from_fits_file
    hdul=pf.open(filename)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 214, in fitsopen
    return HDUList.fromfile(
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 482, in fromfile
    return cls._readfrom(
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/astropy/io/fits/hdu/hdulist.py", line 1248, in _readfrom
    raise OSError("Empty or corrupt FITS file")
OSError: Empty or corrupt FITS file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 565, in get_query_products
    prod_list = self.build_product_list(instrument,res, scratch_dir,api=api)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_spectrum_query.py", line 507, in build_product_list
    spectrum_list = JemxSpectrumProduct.build_list_from_ddosa_res(res,
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_osa_plugin/osa_spectrum_query.py", line 168, in build_list_from_ddosa_res
    logger.error("unable to open %s : %s", spec_filename, e)
NameError: name 'logger' is not defined
```

**Comment by volodymyrss** [comment]
I think @ferrigno saw it. I think the data is empty some how (maybe it's expected) but the error is not good
