### ISSUE TITLE
isgri LC problem

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#26]
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 581, in process_query_product
    process_products_query_out=self.process_product(instrument,self.query_prod_list,api=api,config=config,**kwargs)
  File "/usr/local/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 554, in process_product
    query_out= self.process_product_method(instrument, query_prod_list, api=api, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/cdci_osa_plugin/osa_lightcurve_query.py", line 413, in process_product_method
    _html_fig.append(query_lc.get_html_draw())
  File "/usr/local/lib/python3.8/site-packages/cdci_osa_plugin/osa_lightcurve_query.py", line 233, in get_html_draw
    dx = data['TIMEDEL']*0.5
  File "/usr/local/lib/python3.8/site-packages/astropy/io/fits/fitsrec.py", line 507, in __getitem__
    return self.field(key)
  File "/usr/local/lib/python3.8/site-packages/astropy/io/fits/fitsrec.py", line 694, in field
    column = self.columns[key]
  File "/usr/local/lib/python3.8/site-packages/astropy/io/fits/column.py", line 1644, in __getitem__
    key = _get_index(self.names, key)
  File "/usr/local/lib/python3.8/site-packages/astropy/io/fits/column.py", line 2046, in _get_index
    raise KeyError(f"Key '{key}' does not exist.")
KeyError: "Key 'TIMEDEL' does not exist."
ERROR:cdci_data_analysis.flask_app.dispatcher_query:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/astropy/io/fits/column.py", line 2037, in _get_index
    indx = names.index(key.rstrip())
ValueError: 'TIMEDEL' is not in list
```

**Comment by ferrigno** [comment]
If you use lc_pick, TIMEDEL is not a column in ISGRI and JEM-X, but it is a column in JEM-X detector light curves.

**Comment by volodymyrss** [comment]
It would seem it was introduced to make it OGIP compliant here https://github.com/oda-hub/dispatcher-plugin-integral/commit/6dff693458893a9b60c48c169703b65ace9be821

And then broken somewhere after, maybe in relation to this:

https://github.com/oda-hub/dispatcher-plugin-integral/commit/5816a366b20fa147bcef0ba2d808e28d97e86fcd

Since we had no consistent test until last Friday, we do not known when and why.
I guess I will re-enable ogip compliant function and try to make it work.

**Comment by volodymyrss** [comment]
so it is related to https://github.com/oda-hub/dispatcher-plugin-integral/issues/9

**Comment by volodymyrss** [comment]
ah so it is probably this same patch applied now in lc_pick?

**Comment by ferrigno** [comment]
It should be the same patch of lc_pick. I assumed lc_pick is used in ODA and then, we disabled it with Andrea.

**Comment by ferrigno** [comment]
The interface between production of light curve and pulgin was never clarified in a doc. I assumed it is OSA (so lc_pick), but it is not, hence the confusion.

**Comment by volodymyrss** [comment]
that's fine, we just need to finalize freezing this interface in the present test. That way the interface will be tested with every further change and will no more break.
I am doing it.

**Comment by volodymyrss** [comment]
this particular  problem is resolved by https://github.com/oda-hub/dispatcher-plugin-integral/pull/29
