### ISSUE TITLE
AttributeError: 'OSAVersion' object has no attribute '_units'

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/dispatcher-plugin-integral#62]
```python
WARNING:[ InstrumentQueryBackEnd : instrument-not-set ]:after clear_temp_dir 2.7239949703216553 s
INFO:cdci_data_analysis.flask_app.dispatcher_query:constructed <class 'cdci_data_analysis.flask_app.dispatcher_query.InstrumentQueryBackEnd'>:[ InstrumentQueryBackEnd : isgri ] for data_server_call_back=False
ERROR:cdci_data_analysis.flask_app.app:Exception on /api/meta-data [GET]
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask_restx/api.py", line 672, in error_router
    return original_handler(e)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/flask_app/app.py", line 68, in run_api_meta_data
    return query.get_meta_data()
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/flask_app/dispatcher_query.py", line 656, in get_meta_data
    l.append(self.instrument.get_parameters_list_as_json(prod_name=prod_name))
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/instrument.py", line 396, in get_parameters_list_as_json
    l.append(_query.get_parameters_list_as_json(prod_dict=self.query_dictionary))
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 247, in get_parameters_list_as_json
    l.append(par.reprJSON())
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/parameters.py", line 305, in reprJSON
    return dict(name=self.name, units=self.units, value=self.value)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/parameters.py", line 218, in units
    return self._units
AttributeError: 'OSAVersion' object has no attribute '_units'
```

**Comment by volodymyrss** [comment]
need to add test for instrument description

**Comment by volodymyrss** [comment]
units are meaningless here, but it should be treated safely everywhere

**Comment by volodymyrss** [comment]
> Is it intended?

It's hard to think what the units should be in this case. So since units are meaningless here, dispatcher should allow it. Some adaptation in the plugin for clarity may be needed too.

**Comment by burnout87** [comment]
> > Is it intended?
> 
> It's hard to think what the units should be in this case. So since units are meaningless here, dispatcher should allow it. Some adaptation in the plugin for clarity may be needed too.

Indeed I see that `OSAVersion` is also a Name parameter, which are string, I was thinking that that should be the unit

**Comment by volodymyrss** [comment]
> > > Is it intended?
> > 
> > 
> > It's hard to think what the units should be in this case. So since units are meaningless here, dispatcher should allow it. Some adaptation in the plugin for clarity may be needed too.
> 
> Indeed I see that `OSAVersion` is also a Name parameter, which are string, I was thinking that that should be the unit

`Units` is physical characteristic here. String is not a unit. Unit's make no sense for values which are not float.

**Comment by burnout87** [comment]
I agree, what I meant is that in the code (within the `Name` class) string is used as the unit, but now this was nor properly assigned to a OSAVersion instance.

**Comment by volodymyrss** [comment]
oh, this is misleading. It should not be. But we can keep it for now, it's an easy change. I can not do it today.

**Comment by burnout87** [comment]
I am actually working on it now, PR is on the way, and we can take it from there

**Comment by volodymyrss** [comment]
great, thanks!
